### ISSUE TITLE
Update precipitation input from Thompson MP to RUC LSM when dtf /= dtp

### ISSUE THREAD

**Issue by tanyasmirnova** [NOAA-GSL/ccpp-physics#11]
Dom,
I think the last part of the following code in the GFS_MP_generic.F90 could be also done for RUC in case dtf /= dtp:
if (lsm==lsm_ruc) then
        if (imp_physics == imp_physics_gfdl .or. imp_physics == imp_physics_thompson) then

      if (lsm==lsm_ruc .or. lsm==lsm_noahmp) then
            raincprv(:)   = rainc(:)
            rainncprv(:)  = frain * rain1(:)
            iceprv(:)     = ice(:)
            snowprv(:)    = snow(:)
            graupelprv(:) = graupel(:)
        !for NoahMP, calculate precipitation rates from liquid water equivalent thickness for use in next time step
        !Note (GJF): Precipitation LWE thicknesses are multiplied by the frain factor, and are thus on the dynamics time step, but the conversion as written
        !            (with dtp in the denominator) assumes the rate is calculated on the physics time step. This only works as expected when dtf=dtp (i.e. when frain=1).
        if (lsm == lsm_noahmp) then
          tem = 1.0 / (dtp*con_p001) !GJF: This conversion was taken from GFS_physics_driver.F90, but should denominator also have the frain factor?
          draincprv(:)   = tem * raincprv(:)
          drainncprv(:)  = tem * rainncprv(:)
          dsnowprv(:)    = tem * snowprv(:)
          dgraupelprv(:) = tem * graupelprv(:)
          diceprv(:)     = tem * iceprv(:)
        end if
      end if

What do you think?
Thanks,
Tanya

_Originally posted by @tanyasmirnova in https://github.com/NOAA-GSD/ufs-weather-model/pull/7#issuecomment-579903661_

**Comment by climbfuji** [comment]
@tanyasmirnova is this still an issue? Should we fix this together with https://github.com/NOAA-GSD/ccpp-physics/issues/31 in a small PR?

**Comment by tanyasmirnova** [comment]
Dom,
Yes, it is still an issue, although so far we never used different time step in dynamics and physics. But in case we do, the existing code for RUC LSM will be wrong.. 
It will be great if we could add a small PR to #31. The change in GFS_MP_generic.F90 should be accompanied with the modifications in sfc_drv_ruc.meta and sfc_drv_ruc.F90 to use the d* precipitation variables.

**Comment by climbfuji** [comment]
Tanya, when making this change the units of the precip variables going into RUC will change from `m` to `mm s-1`. Right now, `sfc_drv_ruc.F90` is converting `m` to `mm` by multiplying with `rhoh2o`, and then passing it to `lsmruc`.

`lsmruc` expects
```
!-- RAINCV          one time step convective precipitation (mm/step)
...
```
hence if I was to pass in the `d*` precipitation variables, I would have to multiply it again with `dtp` to get per timestep variables, and except for not having to do the `m` -> `mm `conversion, we wouldn't gain anything. Also note Grant's comment that the conversion you noted in `GFS_MP_generic_post_run` only works for `dtp = dtf`, i.e. `frain = 1`:
```
        !Note (GJF): Precipitation LWE thicknesses are multiplied by the frain factor, and are thus on the dynamics time step, but the conversion as written
        !            (with dtp in the denominator) assumes the rate is calculated on the physics time step. This only works as expected when dtf=dtp (i.e. when frain=1).
        tem = 1.0 / (dtp*con_p001) !GJF: This conversion was taken from GFS_physics_driver.F90, but should denominator also have the frain factor?
```

**Comment by climbfuji** [comment]
@tanyasmirnova I think we can close this issue without taking any action based on what I wrote yesterday (please do so if you agree)

**Comment by tanyasmirnova** [comment]
@climbfuji will the existing RUC code work fine with different dynamic and physics time steps?

**Comment by climbfuji** [comment]
> @climbfuji will the existing RUC code work fine with different dynamic and physics time steps?

I wouldn't vouch for this. But most of the physics, and certainly the GFS physics, will not work correctly if `dtf /= dtp`. I don't think using this option is on the table anywhere in the near future.

Thus, even if you implement it correctly in RUC, other parts of the suite (a lot of the interstitial code) will still create wrong results.

**Comment by tanyasmirnova** [comment]
Thank you, Dom. We can close this PR.
