### ISSUE TITLE
A problem with the NWFA2D initialization in Thompson MP

### ISSUE THREAD

**Issue by tanyasmirnova** [NOAA-GSL/ccpp-physics#13]
The initialization of the NWFA2d is wrong. The field is not physical, but has weird discontinuity lines within the six tiles:

<img width="617" alt="Screen Shot 2020-02-04 at 6 41 07 PM" src="https://user-images.githubusercontent.com/38667904/73803749-f0d28000-477e-11ea-9c6b-bbd81ea70765.png">

Tanya

**Comment by DomHeinzeller** [comment]
This has been fixed by https://github.com/NOAA-GSD/ccpp-physics/pull/14
